name: Test Django App

on: 
  pull_request:

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        name: Checkout
      - name: Build and Test
        run: |
          cd deployment
          docker-compose -f docker-compose.test.yml up --build -d db-test uwsgi-test
          sleep 30
          docker-compose -f docker-compose.test.yml exec -T uwsgi-lite python manage.py test --verbosity=2
